//DESTA MANEIRA CONSEGUIMOS COMENTAR O CODIGO SEM QUE ISSO SEJA EXECUTADO PELO SERVIDOR
/*
*DESTE JEITO CONSEGUIMOS FAZER VARIAS LINHA DE COGIGO
* SEM QUE SEJA EXECUTADO PELO INTERPLETADOR DE CODIGO
 */
//MENSAGEM DE ALERTA
alert("Hello");

//Mensagem visivel apena no console de debug do google
console.log('DEF');
